# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

def app_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyRecipeApp
  pod 'Alamofire',                          '~> 5.4.4'
  pod 'AlamofireImage',                     '~> 4.2.0'
  pod 'AlamofireNetworkActivityIndicator',  '~> 3.1.0'
  pod 'AlamofireNetworkActivityLogger',     '~> 3.4.0'
  pod 'R.swift',                            '~> 7.3.2'
  pod 'SDWebImage',                         '~> 5.18.1'
  pod 'SVProgressHUD',                      '~> 2.2.5'
  pod 'Valet',                              '~> 4.2.0'
  
  # Firebase
  pod 'FirebaseCore',                       '~> 10.15.0'
  pod 'FirebaseAuth',                       '~> 10.15.0'
  pod 'FirebaseFirestore'
  pod 'FirebaseStorage'
end

target 'MyRecipeApp' do
  use_frameworks!
  app_pods
  
  target 'MyRecipeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

post_install do |installer|
  
  puts "Removing static analyzer support for all targets."
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
        config.build_settings['OTHER_CFLAGS'] = "$(inherited) -Qunused-arguments -Xanalyzer -analyzer-disable-all-checks"
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = "YES"

        # This will solve issue if using M1
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64 i386"

        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'

        if target.name == 'iosMath-mathFonts'
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
    end
  end

end

